version: '3'
services:
  lpvis:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace
    image: lpvis
    container_name: lpvis
    tty:
      true
    restart: always

  jlab:
    build:
      context: .
      dockerfile: Dockerfile.jlab
    volumes:
      - ..:/workspace
    image: jlab_tomoino
    container_name: jlab_tomoino
    ports:
      - 8888:8888
    environment:
      GRANT_SUDO: "yes"
      JUPYTER_ENABLE_LAB: "yes"
    command: jupyter-lab --allow-root --ip=0.0.0.0 --port=8888 --no-browser --NotebookApp.token='' --NotebookApp.password='' --notebook-dir=/workspace
    user:
      "root"
    restart: always
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #         - count: all
    #         - capabilities: [gpu]